### ISSUE TITLE
Addons with Description of 256+ characters prevent catalog from loading

### ISSUE THREAD

**Issue by rainecheck** [ogri-la/wowman#129]
I've had wowman failing to load the catalog for a day or two. Even when verbose was set to debug, it would still just pause after the first `"Elapsed time: <blah> msecs"`. If the Update All button was pressed during this pause, it would update 14~ of my addons, not having processed from the 15th addon by alpha.
Managed to get wowman to spit out an error when forcing it to swap between Full and Short catalog when it was paused there: 

```
org.h2.jdbc.JdbcSQLDataException: Value too long for column """DESCRIPTION"" VARCHAR(255) SELECTIVITY 74": "'Changes your reputation bar colors from the standard green to colours that match your current faction level.  Neutral = Gray, F... (256)"; SQL statement:
                                  INSERT INTO catalog (description, alt_name, classic_track, download_count, name, source, retail_track, label, uri, source_id, updated_date) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [22001-199]
                SQL: "INSERT INTO catalog (description, alt_name, classic_track, download_count, name, source, retail_track, label, uri, source_id, updated_date) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
           SQLState: "22001"
          errorCode: 22001
    originalMessage: "Value too long for column \"\"\"DESCRIPTION\"\" VARCHAR(255) SELECTIVITY 74\": \"'Changes your reputation bar colors from the standard green to colours that match your current faction level.  Neutral = Gray, F... (256)\""
```
There are currently there are 3~ addons in the full catalog with excessive descriptions, can be found with the regex `"description":(\n\s*)".{255}`, they are:
 - combatnumbersseparator
 - dwmrepcoloredbars
 - libtoteminfo

Removing these manually from full-catalog allows updates to proceed as normal.
Suggest that either the catalog has the descriptions trimmed, that wowman sanitises the input, or both.

**Comment by torkus** [comment]
Thank you for reporting, @rainecheck 

I updated the catalog about this time yesterday, so it's probably been present since then. Investigating now.

**Comment by torkus** [comment]
[0.12.3](https://github.com/ogri-la/wowman/releases/tag/0.12.3) has been released with a fix in it. 

Thank you for your patience.

**Comment by torkus** [comment]
two of those addons (`combatnumbersseparator` and `libtoteminfo`) looks like curseforge is now encoding UTF-8 chars. 

`dwmrepcoloredbars` looks like a new, genuinely long, description

for example:

> Simple addon, which adds a separator in damage and healing done / Простой аддон, который добавляет запятую в шрифт урона и исцеления.

is now

> Simple addon, which adds a separator in damage and healing done / \u041f\u0440\u043e\u0441\u0442\u043e\u0439 \u0430\u0434\u0434\u043e\u043d, \u043a\u043e\u0442\u043e\u0440\u044b\u0439 \u0434\u043e\u0431\u0430\u0432\u043b\u044f\u0435\u0442 \u0437\u0430\u043f\u044f\u0442\u0443\u044e \u0432 \u0448\u0440\u0438\u0444\u0442 \u0443\u0440\u043e\u043d\u0430 \u0438 \u0438\u0441\u0446\u0435\u043b\u0435\u043d\u0438\u044f.

distributing `json` as `ascii` with encoded utf-8 codepoints is pretty standard. I wonder what made them switch.

**Comment by rainecheck** [comment]
Thanks for the quick turnaround, much appreciated :)
