### ISSUE TITLE
java.lang.UnsupportedOperationException on arch linux

### ISSUE THREAD

**Issue by lyinch** [ogri-la/wowman#138]
Hey,

I tried using the client on arch linux from AUR https://aur.archlinux.org/packages/wowman/ and get an unsupported operation exception when trying to clicking on an addon like Questi from Curse in the search.

```
"Elapsed time: 25.444061 msecs"
"Elapsed time: 1158.815736 msecs"
"Elapsed time: 1059.374843 msecs"
2020-04-19 17:47:16.254 deadbeef ERROR [wowman.main:22] - Uncaught exception on AWT-EventQueue-1
                                              java.awt.EventDispatchThread.run  EventDispatchThread.java:   82
                                       java.awt.EventDispatchThread.pumpEvents  EventDispatchThread.java:   93
                                       java.awt.EventDispatchThread.pumpEvents  EventDispatchThread.java:  101
                           java.awt.EventDispatchThread.pumpEventsForHierarchy  EventDispatchThread.java:  105
                              java.awt.EventDispatchThread.pumpEventsForFilter  EventDispatchThread.java:  116
                           java.awt.EventDispatchThread.pumpOneEventForFilters  EventDispatchThread.java:  205
                                             java.awt.EventQueue.dispatchEvent           EventQueue.java:  730
 java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege     ProtectionDomain.java:   74
                                   java.security.AccessController.doPrivileged      AccessController.java     
                                                     java.awt.EventQueue$4.run           EventQueue.java:  731
                                                     java.awt.EventQueue$4.run           EventQueue.java:  733
 java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege     ProtectionDomain.java:   84
 java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege     ProtectionDomain.java:   74
                                   java.security.AccessController.doPrivileged      AccessController.java     
                                                     java.awt.EventQueue$3.run           EventQueue.java:  703
                                                     java.awt.EventQueue$3.run           EventQueue.java:  709
                                                java.awt.EventQueue.access$500           EventQueue.java:   97
                                         java.awt.EventQueue.dispatchEventImpl           EventQueue.java:  760
                                              java.awt.Component.dispatchEvent            Component.java: 4711
                                             java.awt.Window.dispatchEventImpl               Window.java: 2746
                                          java.awt.Container.dispatchEventImpl            Container.java: 2283
                                  java.awt.LightweightDispatcher.dispatchEvent            Container.java: 4476
                              java.awt.LightweightDispatcher.processMouseEvent            Container.java: 4544
                             java.awt.LightweightDispatcher.retargetMouseEvent            Container.java: 4904
                                              java.awt.Component.dispatchEvent            Component.java: 4711
                                          java.awt.Container.dispatchEventImpl            Container.java: 2297
                                          java.awt.Component.dispatchEventImpl            Component.java: 4889
     seesaw.swingx.proxy$org.jdesktop.swingx.JXTable$Tag$fd407141.processEvent                                
                                               java.awt.Container.processEvent            Container.java: 2239
                                               java.awt.Component.processEvent            Component.java: 6304
seesaw.swingx.proxy$org.jdesktop.swingx.JXTable$Tag$fd407141.processMouseEvent                                
                                      javax.swing.JComponent.processMouseEvent           JComponent.java: 3324
                                          java.awt.Component.processMouseEvent            Component.java: 6542
                                     java.awt.AWTEventMulticaster.mouseClicked  AWTEventMulticaster.java:  270
                                            seesaw.event/fn/reify/mouseClicked                 event.clj:  290
                                                             seesaw.event/fire                 event.clj:  263
                       wowman.ui.gui/installed-addons-go-links/go-link-clicked                   gui.clj:  436
                                                                           ...                                
                                       orchestra.spec.test/spec-checking-fn/fn                  test.clj:  125
                                                                           ...                                
                                                       wowman.ui.gui/browse-to                   gui.clj:  103
                                                       java.awt.Desktop.browse              Desktop.java:  380
                                           java.awt.Desktop.checkActionSupport              Desktop.java:  221
java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
```

with

```
$ java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
```

**Comment by torkus** [comment]
Thank you for opening a ticket, I really do appreciate the feedback.

If I'm to fix this I need to be able to replicate your problem for myself otherwise I'm just stumbling about in the dark.

My *suspicion* is that this happened when you clicked the blue 'link' in the search tab under the 'source' column. Is that correct? Also, do you have installed a popular desktop like Gnome/Mate/XFCE/KDE?

Could you run the below command in a terminal and let me know it's output?

    $ whereis xdg-open gnome-open kde-open

for me it looks like:

    xdg-open: /usr/bin/xdg-open /usr/share/man/man1/xdg-open.1.gz
    gnome-open:
    kde-open:

**Comment by lyinch** [comment]
Hey,

```
$ whereis xdg-open gnome-open kde-open
xdg-open: /usr/bin/xdg-open /usr/share/man/man1/xdg-open.1.gz
gnome-open:
kde-open:
```

and `$ xdg-open "http://www.google.com"` opens the URL in firefox. I use bspwm as window manager.

You're right, I wasn't very precise. The error appears when I click on the blue link in the source field, like `curseforge`. As this runs in the JVM, note that I'm also using `wmname LG3D`. The reason is that Java AWT doesn't like non-reparenting window managers according to: https://www.reddit.com/r/bspwm/comments/267srd/problem_with_intellij_bspwm/ and some SO threads.


I also found something interesting:

> Use the isDesktopSupported() method to determine whether the Desktop API is available. On the Solaris Operating System and the Linux platform, this API is dependent on Gnome libraries. If those libraries are unavailable, this method will return false. After determining that the Desktop API is supported, that is, the isDesktopSupported() returns true, the application can retrieve a Desktop instance using the static method getDesktop().
from https://docs.oracle.com/javase/tutorial/uiswing/misc/desktop.html . 

However, using
```$ sudo ln -s /usr/bin/xdg-open /usr/bin/gnome-open``` doesn't help, so the presence of the binary isn't enough.

**Comment by lyinch** [comment]
Hey, sorry for double posting but I think I found the issue. I don't know clojure but it looks like it's (at least) this line:

https://github.com/ogri-la/wowman/blob/develop/src/wowman/ui/gui.clj#L103

I tried to reproduce the java awt call:

```
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

public class Main {
    public static void main(String args[]) throws URISyntaxException, IOException {
        Desktop desktop = Desktop.getDesktop();
        desktop.browse(new URI("http://www.google.com"));
    }
}
```

and I get the same error

```
Exception in thread "main" java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
	at java.awt.Desktop.checkActionSupport(Desktop.java:221)
	at java.awt.Desktop.browse(Desktop.java:380)
	at Main.main(Main.java:11)
```

You can use
```
if(Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)){
            Desktop desktop = Desktop.getDesktop();
            desktop.browse(new URI("http://www.google.com"));
        }
``` 

because `Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)` returns `false` on my machine. And then to open a URL you can use `runtime.exec("xdg-open " + "http://www.google.com/")` . I guess it's similar in clojure. Or to be double safe, also check if the `xdg-open` binary exists. I have this from:
https://stackoverflow.com/questions/5226212/how-to-open-the-default-webbrowser-using-java

**Comment by torkus** [comment]
Thanks for posting your own investigation. I took a look earlier and came to a similar conclusion. I'll do some tests for Java handling to begin with and then fallback to looking for more specific handlers like gnome-open, kde-open then xdg-open and if absolutely nothing works I'll pop up a dialogue where the url can be copied and pasted. I'll get you to test a candidate release. For now it should be usable if you avoid clicking on those links.

**Comment by torkus** [comment]
Below is a pre-release of `0.12.4` with a fix that attempts several other methods of opening a link before failing less noisily:

---
[wowman-0.12.4-unreleased-standalone.jar.zip](https://github.com/ogri-la/wowman/files/4504420/wowman-0.12.4-unreleased-standalone.jar.zip)
sha256: 3237fa5ebea9c6e0d7c3578d07eef0357c93c0fcadb983e5c5e83f9e3094fe84

---

You can execute it with `java -jar wowman-0.12.4-unreleased-standalone.jar.zip` (no need to remove the `.zip` extension).

Please let me know if this works for you.

**Comment by lyinch** [comment]
Hey, it works.

```
:info	16:25:46 - opening URL with xdg-open: https://www.wowinterface.com/downloads/info24994
``` 

Thank you

**Comment by torkus** [comment]
Thanks for your time and testing, @lyinch . `0.12.4` has just been released and you can download it via the AUR. Closing issue.
