### ISSUE TITLE
link to addons.org/downloader.html

### ISSUE THREAD

**Issue by mooreatv** [ogri-la/wowman#29]
Hi there

would you mind adding a link to
https://wowaddons.org/downloader.html
in your list ?

also join the effort :)

https://discord.gg/t8msyQU

**Comment by torkus** [comment]
sure, I can add wowaddons.org to the list

> also join the effort :)

I'm not a joiner, but good luck.

**Comment by torkus** [comment]
actually, I'm a little confused, this doesn't look like an addon manager but some sort of OSS policy discussion thing. I'm happy to link to your software if you have any

**Comment by ldemailly** [comment]
the stage right now is build vs reuse, I haven’t gone yet through every option to see if one meets the requirements either as a starting point or even ready solution

i guess you can table this request until/if we decide to build yet another one

thx!

**Comment by mooreatv** [comment]
the stage right now is build vs reuse, I haven’t gone yet through every option to see if one meets the requirements either as a starting point or even ready solution

i guess you can table this request until/if we decide to build yet another one

thx!

**Comment by torkus** [comment]
well, good luck with whatever you decision is. 

closing for now
