### ISSUE TITLE
erikabp123/ClassicAddonManager

### ISSUE THREAD

**Issue by Ketho** [ogri-la/wowman#32]
There is https://github.com/erikabp123/ClassicAddonManager if you could check it and add it to the list

https://www.reddit.com/r/classicwow/comments/cqe292/classic_addon_manager_curse_and_github_support/

**Comment by torkus** [comment]
Sure thing, I can do this later today. Thanks for putting in the hard work. 

I think the only other Java client on the list is Minion, the official wowinterface.com client

**Comment by torkus** [comment]
all done :)
