### ISSUE TITLE
Grid2 paired with Grid

### ISSUE THREAD

**Issue by layday** [ogri-la/wowman#42]
I thought I would conduct some - uhh - market research before adding a matcher to instawow (or maybe I'll just end up using wowman) when I stumbled across this one:

<img width="1053" alt="Screenshot 2019-09-13 at 15 24 26" src="https://user-images.githubusercontent.com/31134424/64862225-a1a67a00-d63a-11e9-8437-b5e58cd99250.png">

I assume it falls prey to the `rm-trailing-version` function of the TOC parser.

**Comment by torkus** [comment]
hey, thanks for raising the issue. 

> I thought I would conduct some - uhh - market research

it's fine, wowman can't be all things to all people. It certainly can't be as good on the command line as instawow.

so, the problem here is that you installed the 'grid2' addon and it's matching against the 'grid' addon? I can replicate this, investigating.

**Comment by torkus** [comment]
> I assume it falls prey to the rm-trailing-version function of the TOC parser.

I think you're right and that regex is a bit too heavy-handed. If you're looking at my matching code, then you may have seen this already, but the list of toc file derived values to match against the catalog are specified here: https://github.com/ogri-la/wowman/blob/develop/src/wowman/core.clj#L488-L490

The code goes through each pair until a match is found. I coincidentally revisited that code just the other day as I'm introducing an in-memory database to do this catalog matching for me. The `idx-idx-idx` stuff that's in there at the moment is impenetrable and I've replaced it with this: https://github.com/ogri-la/wowman/blob/db-support/src/wowman/core.clj#L529-L567

a little more readable but it's still just an investigation

**Comment by torkus** [comment]
[This PR](https://github.com/ogri-la/wowman/pull/43) tightens up the conditions under which the trailing digits are stripped. It will prevent this case with 'Grid2' (and probably many similar others), but [it's not perfect](https://github.com/ogri-la/wowman/pull/43/files#diff-4c1a3d9e0b1f26ae1add9f081506d0eaR85) and I may drop the suffix stripping on this value in the future - create some new lookup instead

**Comment by torkus** [comment]
@layday , if this bug is a showstopper for you then let me know and I'll do a 0.9.1 patch release tomorrow, otherwise I'll eventually roll it out with 0.10.0

**Comment by layday** [comment]
Oh no, I can still install the right Grid from the catalogue.  Thanks for fixing it so quickly.

**Comment by torkus** [comment]
> Oh no, I can still install the right Grid from the catalogue. 

yes, just for anybody else reading this bug: this only affects addons *not* installed by wowman *or* addons installed by wowman but you decided to delete the `.wowman.json` file for some reason.

> Thanks for fixing it so quickly.

My pleasure. Merging PR, closing ticket
