### ISSUE TITLE
Update list for grrttedwards/wow-addon-updater

### ISSUE THREAD

**Issue by grrttedwards** [ogri-la/wowman#57]
The existing entry for kuhnertdm/wow-addon-updater is marked `unmaintained`. I have taken over updating it for now, and am most current on the network graph.
Let's update the entry to list my fork https://github.com/grrttedwards/wow-addon-updater as actively maintained.

**Comment by torkus** [comment]
hey @grrttedwards , I have no problem adding your fork to the list.

Did you and @dark0dave come to an understanding?

**Comment by grrttedwards** [comment]
I don't really know what happened there, and he has since removed me from his GitLab. If you're uncomfortable putting me on the list, that's okay.

...It looks like he spent quite some time blatantly copying my project refactor. So he's now twice ripped off people's work he found on GitHub.

**Comment by layday** [comment]
I'm confused as to what you mean by 'ripped off'.  Did he reuse bits of your code failing to give attribution?  The original wow-addon-updater and both of your forks are licensed under the GPLv3, meaning they can 'blatantly copy' any part of your refactor if they comply with the terms of the licence.

**Comment by grrttedwards** [comment]
The reason there was a back-and-forth is because I disagreed with the original move to GitLab, and references to the original author were wiped from the repository. I'm just pointing out that that's now happened twice. I'm aware there is no licensing issue.

**Comment by torkus** [comment]
List has been updated. Thanks for being civil guys :)

**Comment by layday** [comment]
Only tangentially relevant but I didn't feel like it warranted opening a new bug - the asterisks on antiwinter/wowa and instawow seem to imply that they don't work on any platform.

**Comment by torkus** [comment]
> * with caveats. may require compilation, partial functionality or not work at all, or be officially unsupported, or ...

It's definitely vague and inconsistently applied.

The intent was to mark those projects that don't have a simple executable release for that platform. To use it you would have to do other things first, like install git or java or python or create a virtualenv (or use pipx) or compile the code or figure out Docker or snaps or whatever. This is a big deal for the poor souls using Windows, possible Mac users as well, I don't know. Much less of a deal in Linux land. Or the developer has explicitly stated that it will only be supported on certain platforms.

If the asterisk means "inconvenient to install" I'd then need to explain "inconvenient for whom?"

What would you consider inconvenient?

**Comment by layday** [comment]
I feel like it's the norm for a CLI built in an interpreted language that it wouldn't be compiled (or packaged, rather) into an executable, so that doesn't really tell me anything I couldn't gleam from the language column - it just leaves me wondering how wowa might be broken on my OS.

**Comment by layday** [comment]
I suppose this kinda fits into OS philosophy and the audience of the add-on manager.  Whereas a Windows user might just look for an .exe to download - even if it is for a CLI - on Linux or Mac my first instict would be to use my package manager (e.g. dnf or nix).

**Comment by torkus** [comment]
We're developers and we don't see the world as non-developers. Our expectations are different.

I want some way to indicate to a regular WoW player who goes to this list to download software that it's not going to be a straightforward installation. They're going to have to be a developer as well to understand things like Python and interpreted languages and why and how these prerequisites are necessary.

WoWMatrix, whatever their reputation, is painless to install on all platforms. This is the bar I hold all other addon managers to, including my own.

I'm open to suggestions for improvement as well as pull requests. I'll definitely revisit the asterisks, but not tonight. Perhaps this weekend I'll toy with a better presentation for the list.

> I suppose this kinda fits into OS philosophy and the audience of the add-on manager. Whereas a Windows user might just look for an .exe to download - even if it is for a CLI - on Linux or Mac my first instict would be to use my package manager (e.g. dnf or nix).

I was thinking something similar. Perhaps caveat the Windows and Mac platforms? On a Mac I guess I'd expect a `.dmg` to be available. Windows an exe. Linux would only get an asterisk if the prerequisite tasks were too onerous, like having to install an old version of QT or additional system packages with no native package available for at least one platform.

**Comment by torkus** [comment]
Also, I'm fine with you creating a new ticket to chat about whatever is on your mind.

**Comment by layday** [comment]
> On a Mac I guess I'd expect a `.dmg` to be available.

If it is a GUI, then yes, either a disk image or a zip file.  You can't invoke a Mac app - an app is a folder masquerading as an executable - you have to navigate _inside_ the app bundle to look for something you might be able to run from the command line.

**Comment by torkus** [comment]
can you launch the terminal with the app running as the 'gui'?

**Comment by layday** [comment]
You can, if you are able to locate the executable:

```
$ open LibreOffice.app
$ LibreOffice.app --version
fish: Unknown command LibreOffice.app
$ ps -A | grep LibreOffice
16847 ??         0:03.34 /Users/xyz/Applications/LibreOffice.app/Contents/MacOS/soffice
16853 ttys000    0:00.00 grep --color=auto LibreOffice
$ LibreOffice.app/Contents/MacOS/soffice --version
LibreOffice 6.3.2.2 98b30e735bda24bc04ab42594c85f7fd8be07b9c
```
