### ISSUE TITLE
wowinterface, curseforge-like release behaviour observed by addon authors

### ISSUE THREAD

**Issue by torkus** [ogri-la/wowman#62]
This addon appears to be mixing classic and retail releases ala curseforge.

https://www.wowinterface.com/downloads/info24771

I'm sure it's not isolated behaviour. This undermines the assumption that the latest release from wowinterface doesn't have a retail/classic dimension.

**Comment by torkus** [comment]
A couple more cases:

* https://www.wowinterface.com/downloads/info25009
* https://www.wowinterface.com/downloads/info19390 (this one acknowledges a problem)

I've been through the entire diff now and didn't find anything more significant. Not to say it's not more prevalent, but it's definitely not so common I need to start handling it

**Comment by layday** [comment]
Now with support from WoWI: https://www.wowinterface.com/downloads/info24910-WeakAuras2.html.

**Comment by torkus** [comment]
arse.

why can't anything just stand still for like, ten minutes?

![](https://cdn-js.meetedgar.com/wp-content/uploads/2016/04/Mr-Incredible-Interview.gif)

**Comment by torkus** [comment]
their 'api' hasn't been updated. I can't make any connection to the classic version of that addon with it.

retail link:
https://www.wowinterface.com/downloads/download24910-WeakAuras2

classic link:
https://www.wowinterface.com/downloads/dlfile425/WeakAuras-2.15.4-classic.zip?1571230790

api result:

```
 181979   {
 181980     "UID": "24910",
 181981     "UICATID": "27",
 181982     "UIVersion": "2.15.4",
 181983     "UIDate": 1571230655000,
 181984     "UIName": "WeakAuras 2",
 181985     "UIAuthorName": "Stanzilla",
 181986     "UIFileInfoURL": "https://www.wowinterface.com/downloads/info24910-WeakAuras2.html",
 181987     "UIDownloadTotal": "48813",
 181988     "UIDownloadMonthly": "7903",
 181989     "UIFavoriteTotal": "40",
 181990     "UICompatibility": [
 181991       {
 181992         "version": "1.13.2",
 181993         "name": "WoW Classic"
 181994       }
 181995     ],
 181996     "UIDir": [
 181997       "WeakAuras",
 181998       "WeakAurasOptions",
 181999       "WeakAurasModelPaths",
 182000       "WeakAurasTemplates"
 182001     ],
 182002     "UIIMG_Thumbs": [
 182003       "https://cdn-wow.mmoui.com/preview/tiny/pvw70990.png"
 182004     ],
 182005     "UIIMGs": [
 182006       "https://cdn-wow.mmoui.com/preview/pvw70990.png"
 182007     ],
 182008     "UISiblings": null,
 182009     "UIDonationLink": "https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&amp;hosted_button_id=FRVH7EYXFDTUN"
 182010   },
```

api detail result:

```json
[
  {
    "UID": "24910",
    "UICATID": "27",
    "UIVersion": "2.15.4",
    "UIDate": 1571230655000,
    "UIMD5": "8b85b17fbf8d7efb2a1183c9cb5e6ca7",
    "UIFileName": "WeakAuras-2.15.4.zip",
    "UIDownload": "https://cdn.wowinterface.com/downloads/getfile.php?id=24910&d=1571230655&minion",
    "UIPending": "0",
    "UIName": "WeakAuras 2",
    "UIAuthorName": "Stanzilla",
    "UIDescription": "",
    "UIChangeLog": "# [2.15.4](https://github.com/WeakAuras/WeakAuras2/tree/2.15.4) (2019-10-16)\n\n[Full Changelog](https://github.com/WeakAuras/WeakAuras2/compare/2.15.3...2.15.4)\n\n## Highlights\n\n - hot fix for cast bar issue on retail \n\n## Commits\n\nmrbuds (1):\n\n- cast trigger: don't hide cast bar on UNIT_SPELLCAST_FAILED fixes #1766",
    "UIHitCount": "48814",
    "UIHitCountMonthly": "7903",
    "UIFavoriteTotal": "40"
  }
]
```

I guess it's good it's not breaking anything ...

**Comment by layday** [comment]
> I guess it's good it's not breaking anything ...

Not exactly accurate, you'll notice compatibility is for classic while it's serving the retail version.

**Comment by layday** [comment]
There's also a v4 API corresponding to the as yet unreleased v4 of Minion that suffers from the same issue.  You can see which other add-ons are using the split-version setup by incrementing the `dlfile` counter:

```
$ for i in (seq 500)
      curl -Is https://www.wowinterface.com/downloads/dlfile$i/ | rg -or '$1' 'filename="(\w+)'
  end | rg -v '^(beta|\d)' | sort | uniq
AutomaticGoblinTherapist
BasicChatMods
BecomeMyFriend
BetterVendorPrice
BigWigs
Chinchilla
FriendGroups
LargerMacroIconSelection
Masque
Masque_Apathy
Masque_Caith
Masque_Cirque
Masque_Entropy
NeatMinimap
PixelPerfectAlign
ReagentCount
SlashIn
WeakAuras
idTweaks
```

**Comment by torkus** [comment]
AutomaticGoblinTherapist - 8.2.5
BasicChatMods - 8.2.5
BecomeMyFriend - 8.2.5 and 1.13.2
BetterVendorPrice - 8.2.5
BigWigs - 8.2.5
Chinchilla - 8.2.5
FriendGroups - 1.13.2
LargerMacroIconSelection - 8.2.5
Masque - 1.13.2, 8.2.0, 8.1.5, 8.1.0, 8.0.1

it really is all over the place

**Comment by layday** [comment]
So this renders `UICompatibility` about as useful as the CurseForge `gameVersionFlavor`.

**Comment by layday** [comment]
You can't rely on the category either because you have add-ons in 'Classic - General' that are expressly compatible with retail: https://www.wowinterface.com/downloads/info25261-quantify.html.  It looks like everybody's intent on doing the wrong — thing.

**Comment by torkus** [comment]
> So this renders UICompatibility about as useful as the CurseForge gameVersionFlavor.

Ever so slightly more useful. I don't know what is going on with their API but I'm not dropping back to HTML scraping any time soon.

**Comment by layday** [comment]
I'm fairly confident their API isn't getting updated any time soon - Minion is the API's raison d'etre and it's beginning to look like abandonware.

**Comment by torkus** [comment]
some mutterings in the forum: https://www.wowinterface.com/forums/showthread.php?t=57493 (last two posts)
