### ISSUE TITLE
Git repo as source ?

### ISSUE THREAD

**Issue by elfranne** [ogri-la/wowman#68]
Would it possible to add an addon from a git repo ?
for example: https://github.com/Aviana/HealComm/releases 
is not released on curse or wowinterface.

(maybe an option to use branch or releases)

**Comment by torkus** [comment]
Hi there, thanks for opening a ticket.

`0.10.0` is nearing release and with it comes the ability to switch between catalogs of addons. 

`wowman` provides `short`, `full`, `curseforge` and `wowinterface` catalogs, with `full` being absolutely everything and `short` being derived from `full` excluding addons that haven't been updated since 2016. 

Being able to support multiple catalogs was a baby step towards supporting a decentralised user-controlled catalog for addon authors who choose to *not* use any of the big addon hosts, like wowinterface or curseforge.

Some big problems that will need to be thought about a bit more:
1. responsibility. by providing a catalog of github/gitlab/whatever hosted addons I am in fact tacitly endorsing the quality of these addons and that they are not malicious. Right now, it's wowinterface or curseforge taking that responsibility on their shoulders.
2. consistency. I can't have special rules for specific addons on github/gitlab/etc - they must all do things in a certain way. For example, branches or releases? Classic or retail or both? Beta or stable? In your example the latest release is a Beta, which wowman doesn't consider when downloading addons from Curseforge. But then again, it *is* on github and it probably *is* targeted at more hardcore fans.
3. coordination. How do addons get on this list? Do I rely on others to nominate them for me? Should I be scraping github search results for candidates? Is there a review process or is the barrier for entry just some dude saying this code is all good? What if someone says an addon should be taken off the list?

Or, I could go down another route and just let users add URLs to repositories directly in `wowman` and behind the scenes build up their own per-user catalog. This seems like the safest most convenient approach, but solving the hardest problems, like problem #3 above, often get you the biggest wins and taking the quickest, safest route can undermine the larger effort so that it never happens.

If you have your own thoughts about how you'd like to see this feature work please let me know, every little bit of insight helps.

**Comment by elfranne** [comment]
I think the easiest would be for the user to provide an url to the repo and an option to either use master branch or use latest release. 

Thanks for making this, really useful !

**Comment by layday** [comment]
> Being able to support multiple catalogs was a baby step towards supporting a decentralised user-controlled catalog for addon authors who choose to not use any of the big addon hosts, like wowinterface or curseforge. [..]

It sounds like you want to have a _centralised_ catalogue of decentralised add-ons.  An alternative would be to let users add catalogs - not to create their own arbitrary catalogs - but to track user-compiled catalogs made available _elsewhere_, and having a spec and schema that catalogs would need to adhere to.  This could borrow from existing packaging solutions.

**Comment by torkus** [comment]
> centralised catalogue of decentralised add-ons
> track user-compiled catalogs made available elsewhere

unless we go down the Freenet/bittorrent/IPFS/etc path, then yes, a single catalogue of add-ons hosted on platforms other than the two biggies.

> having a spec and schema that catalogs would need to adhere to. This could borrow from existing packaging solutions.

I'm not interested in re-inventing the package manager or shepherding cats about. I'll add support for Github using releases, ignore any 'alpha' or 'beta' label munging for the time being, have a 'user' catalogue rather like how a web browser have a 'user' stylesheet and perhaps in the future these user catalogues can be 'published' somewhere, aggregated, shared, whatever.

**Comment by layday** [comment]
> unless we go down the Freenet/bittorrent/IPFS/etc path, then yes, a single catalogue of add-ons hosted on platforms other than the two biggies.

I don't see a parallel between being able to importing catalogs and peer-to-peer networks.  Haven't you ever had to add a repo to apt?  That's more like what I had in mind - an add-on metadata format to standardise on which could be useful more generally, e.g. that I could also add support for in instawow.

**Comment by torkus** [comment]
> That's more like what I had in mind - an add-on metadata format to standardise on which could be useful more generally, e.g. that I could also add support for in instawow.

The [catalogues I make](https://github.com/ogri-la/wowman-data) are on specification version 1 - an adhoc spec that has remained backwards compatible since I released wowman. I have been thinking about a version 2 for the inevitable `1.0.0` release of wowman that would drop support for the v1 spec. If you'd like to make suggestions about what your perfect catalogue spec would look like (in another ticket), something that instawow could use, I'd love to hear it.

**Comment by layday** [comment]
Well, the catalogues as they are don't contain enough information to install an add-on, only to retrieve it from another, host-specific catalogue or API.  But yes, I suppose I've managed to hijack another issue.

**Comment by torkus** [comment]
>  But yes, I suppose I've managed to hijack another issue.

It's fine. Let interesting ideas have their own ticket and we can shoot the breeze there.

**Comment by torkus** [comment]
@elfranne , `0.10.0` has been released and this new feature has been added to the `0.11.0` TODO list. 

November will be busy for me so I don't expect to release `0.11.0` until mid December.

**Comment by torkus** [comment]
I have installation of github addons working:

![Screenshot at 2019-10-21 22-53-14](https://user-images.githubusercontent.com/48790775/67204756-c241cb00-f455-11e9-863d-9770969062ec.png)

There is such huge variability when it comes to these addons that they can only be installed under very specific circumstances. Luckily Aviana/Healcomm meets those requirements.

I need to add some more tests/polish and a GUI widget to input the URL but I'm pleased I was able to find a consistent subset of addons that are following a release procedure that lets us install them. I'll make sure the conditions are written up as well.

**Comment by torkus** [comment]
I have a pre-release here with support for installing addons from Github:

---
[wowman-0.11.0-unreleased-standalone.jar.zip](https://github.com/ogri-la/wowman/files/3774652/wowman-0.11.0-unreleased-standalone.jar.zip)

---
Click `Import/Export` then `Import addon from Github` and enter the URL of the addon you wish to add (like `https://github.com/Aviana/HealComm`).

Addons that can be installed from Github must be using 'releases' and have at least one packaged asset attached to the release.

If the word 'classic' is present in the asset name, it's assumed to be to a Classic version of the addon.

If there are multiple assets in a release and no way to distinguish between them, I default to 'retail' and the first retail asset will be used.

It's a little rough around the edges so let me know how you go.

**Comment by elfranne** [comment]
Using retail as default seems not very practical, you could look into the .toc and find out if it retail/classic. Using the master branch if no release would also be a desired option.

But I get an error when importing HealComm:

```
2019-10-26 22:53:14.210 tom-B450-I-AORUS-PRO-WIFI WARN [wowman.github-api:59] - no 'classic' release available for 'healcomm' on github
2019-10-26 22:53:14.217 tom-B450-I-AORUS-PRO-WIFI ERROR [wowman.main:22] - Uncaught exception on AWT-EventQueue-1
                                             java.awt.EventDispatchThread.run  EventDispatchThread.java:   82
                                      java.awt.EventDispatchThread.pumpEvents  EventDispatchThread.java:   93
                                      java.awt.EventDispatchThread.pumpEvents  EventDispatchThread.java:  101
                          java.awt.EventDispatchThread.pumpEventsForHierarchy  EventDispatchThread.java:  105
                             java.awt.EventDispatchThread.pumpEventsForFilter  EventDispatchThread.java:  116
                          java.awt.EventDispatchThread.pumpOneEventForFilters  EventDispatchThread.java:  205
                                            java.awt.EventQueue.dispatchEvent           EventQueue.java:  730
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege     ProtectionDomain.java:   74
                                  java.security.AccessController.doPrivileged      AccessController.java     
                                                    java.awt.EventQueue$4.run           EventQueue.java:  731
                                                    java.awt.EventQueue$4.run           EventQueue.java:  733
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege     ProtectionDomain.java:   84
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege     ProtectionDomain.java:   74
                                  java.security.AccessController.doPrivileged      AccessController.java     
                                                    java.awt.EventQueue$3.run           EventQueue.java:  703
                                                    java.awt.EventQueue$3.run           EventQueue.java:  709
                                               java.awt.EventQueue.access$500           EventQueue.java:   97
                                        java.awt.EventQueue.dispatchEventImpl           EventQueue.java:  760
                                             java.awt.Component.dispatchEvent            Component.java: 4711
                                            java.awt.Window.dispatchEventImpl               Window.java: 2746
                                         java.awt.Container.dispatchEventImpl            Container.java: 2283
                                 java.awt.LightweightDispatcher.dispatchEvent            Container.java: 4476
                             java.awt.LightweightDispatcher.processMouseEvent            Container.java: 4535
                            java.awt.LightweightDispatcher.retargetMouseEvent            Container.java: 4904
                                             java.awt.Component.dispatchEvent            Component.java: 4711
                                         java.awt.Container.dispatchEventImpl            Container.java: 2297
                                         java.awt.Component.dispatchEventImpl            Component.java: 4889
                                              java.awt.Container.processEvent            Container.java: 2239
                                              java.awt.Component.processEvent            Component.java: 6304
                                     javax.swing.JComponent.processMouseEvent           JComponent.java: 3324
                                         java.awt.Component.processMouseEvent            Component.java: 6539
                 javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased      BasicMenuItemUI.java:  886
                               javax.swing.plaf.basic.BasicMenuItemUI.doClick      BasicMenuItemUI.java:  842
                                           javax.swing.AbstractButton.doClick       AbstractButton.java:  376
                                    javax.swing.DefaultButtonModel.setPressed   DefaultButtonModel.java:  259
                           javax.swing.DefaultButtonModel.fireActionPerformed   DefaultButtonModel.java:  402
                           javax.swing.AbstractButton$Handler.actionPerformed       AbstractButton.java: 2348
                               javax.swing.AbstractButton.fireActionPerformed       AbstractButton.java: 2022
      seesaw.action.proxy$javax.swing.AbstractAction$ff19274a.actionPerformed                                
                                                      seesaw.action/action/fn                action.clj:   90
                                                     wowman.ui.gui/handler/fn                   gui.clj:   99
                                           wowman.ui.gui/import-addon-handler                   gui.clj:  705
                                                                          ...                                
                                      orchestra.spec.test/spec-checking-fn/fn                  test.clj:  125
                                                                          ...                                
                                          wowman.core/add+install-user-addon!                  core.clj:  901
                                                                          ...                                
                                         wowman.core/affects-addon-wrapper/fn                  core.clj:  421
                                                           clojure.core/apply                  core.clj:  659
                                                                          ...                                
                                              wowman.core/install-addon-guard                  core.clj:  513
                                                                          ...                                
                                      orchestra.spec.test/spec-checking-fn/fn                  test.clj:  124
                                orchestra.spec.test/spec-checking-fn/conform!                  test.clj:  113
                                                         clojure.core/ex-info                  core.clj: 4739
clojure.lang.ExceptionInfo: Call to wowman.core/download-addon did not conform to spec:
                            nil - failed: map? in: [0] at: [:args :addon :addon?] spec: :wowman.specs/addon-summary
                            nil - failed: map? in: [0] at: [:args :addon :addon?] spec: :wowman.specs/addon
                            nil - failed: map? in: [0] at: [:args :addon :toc-addon?] spec: :wowman.specs/toc
                            nil - failed: map? in: [0] at: [:args :addon :toc-addon?] spec: :wowman.specs/addon-summary
                            nil - failed: map? in: [0] at: [:args :addon :toc-addon?] spec: :wowman.specs/addon
                            nil - failed: map? in: [0] at: [:args :addon :toc-addon?] spec: :wowman.specs/toc-addon
                            
        clojure.spec.alpha/args: (nil
                                  "/home/tom/Games/world-of-warcraft-2/drive_c/Program Files (x86)/World of Warcraft/_classic_/Interface/AddOns")
     clojure.spec.alpha/failure: :instrument
    clojure.spec.alpha/problems: ({:path [:args :addon :addon?],
                                   :pred clojure.core/map?,
                                   :val nil,
                                   :via
                                   [:wowman.specs/addon-or-toc-addon
                                    :wowman.specs/addon-or-toc-addon
                                    :wowman.specs/addon
                                    :wowman.specs/addon-summary],
                                   :in [0]}
                                  {:path [:args :addon :addon?],
                                   :pred clojure.core/map?,
                                   :val nil,
                                   :via
                                   [:wowman.specs/addon-or-toc-addon
                                    :wowman.specs/addon-or-toc-addon
                                    :wowman.specs/addon],
                                   :in [0]}
                                  {:path [:args :addon :toc-addon?],
                                   :pred clojure.core/map?,
                                   :val nil,
                                   :via
                                   [:wowman.specs/addon-or-toc-addon
                                    :wowman.specs/addon-or-toc-addon
                                    :wowman.specs/toc-addon
                                    :wowman.specs/toc],
                                   :in [0]}
                                  {:path [:args :addon :toc-addon?],
                                   :pred clojure.core/map?,
                                   :val nil,
                                   :via
                                   [:wowman.specs/addon-or-toc-addon
                                    :wowman.specs/addon-or-toc-addon
                                    :wowman.specs/toc-addon
                                    :wowman.specs/addon
                                    :wowman.specs/addon-summary],
                                   :in [0]}
                                  {:path [:args :addon :toc-addon?],
                                   :pred clojure.core/map?,
                                   :val nil,
                                   :via
                                   [:wowman.specs/addon-or-toc-addon
                                    :wowman.specs/addon-or-toc-addon
                                    :wowman.specs/toc-addon
                                    :wowman.specs/addon],
                                   :in [0]}
                                  {:path [:args :addon :toc-addon?],
                                   :pred clojure.core/map?,
                                   :val nil,
                                   :via
                                   [:wowman.specs/addon-or-toc-addon
                                    :wowman.specs/addon-or-toc-addon
                                    :wowman.specs/toc-addon],
                                   :in [0]})
        clojure.spec.alpha/spec: #object[clojure.spec.alpha$regex_spec_impl$reify__2509 0x42727059 "clojure.spec.alpha$regex_spec_impl$reify__2509@42727059"]
       clojure.spec.alpha/value: (nil
                                  "/home/tom/Games/world-of-warcraft-2/drive_c/Program Files (x86)/World of Warcraft/_classic_/Interface/AddOns")
     orchestra.spec.test/caller: {:file "core.clj",
                                  :line 513,
                                  :var-scope wowman.core/install-addon-guard}
```

**Comment by torkus** [comment]
thank you for the bug report, I'll look into it

> Using the master branch if no release would also be a desired option.

I have a suspicion you have a list of Github hosted addons you would like to see supported. If so, could you send me a list of them?

**Comment by torkus** [comment]
updated pre-release with the above bug fixed and a few smaller things:

[wowman-0.11.0-unreleased-standalone.jar.zip](https://github.com/ogri-la/wowman/files/3775454/wowman-0.11.0-unreleased-standalone.jar.zip)
sha256: 306d683d4424accc1a3a79ab6bf6baed1986513fbbe90a46a3904ea4f6b6c35c

It doesn't fix the fact that I can't detect HealComm is a classic addon just from it's release data, but a simple workaround for the time being is to switch the game track to 'retail', install the addon, then switch back to classic. It's a pain I know, but the architecture is changed incrementally and a TODO item has been added for further checks against the files to determine it's game track.

**Comment by torkus** [comment]
updated pre-release with `.toc` file 'peeking' support. It inspects the `.toc` file for the interface version. New support for 'template' attributes that look like `# ## Interface` for those addons that are compiled into multiple releases for different game tracks.

---

[wowman-0.11.0-unreleased-standalone.jar.zip](https://github.com/ogri-la/wowman/files/3882550/wowman-0.11.0-unreleased-standalone.jar.zip)
sha256: 5fde8f2ba63d62b191eaff1d834d8e4ba9d2a7484a927184c913304055cd3bcd

---

I've added [this document](https://github.com/ogri-la/wowman/blob/develop/github-addons.md) on the types of Github addons currently supported with examples.

I've also updated the list of [other addon managers with support for installing from git](https://ogri-la.github.io/wow-addon-managers/?preset/name=unfiltered&field/feature-curseforge=&field/maintained=yes&field/windows=&field/eula=&field/feature-tukui=&field/ads=&field/source-available=&field/feature-wowinterface=&field/ui=&field/language=&field/feature-vcs-addons=yes&field/retail=&field/linux=&field/feature-wowace=&field/f-oss=&field/classic=&field/mac=&field/feature-catalog-search=) you might want to check out 

I may expand support eventually but not for the next release.
