### ISSUE TITLE
Size when starting

### ISSUE THREAD

**Issue by elfranne** [ogri-la/wowman#69]
When starting Wowman the window is very small. This is a very minor annoyance.

Ubuntu 18.04
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)

![Screenshot from 2019-10-12 19-05-22](https://user-images.githubusercontent.com/861038/66707042-21f3f400-ed3b-11e9-9da7-8127d9350c64.png)

Let me know if you need more logs/config.

**Comment by torkus** [comment]
Hi elfranne, thanks for the ticket.

I've been using a tiling window managing for about a decade or longer now which ignores the sizing hints GUI applications send to the window manager. I only discovered the initial window size of wowman was ridiculous after testing it last week on a windows machine !

I'll take a look and if it's easy to do, I'll see it makes it into the `0.10.0` release

**Comment by torkus** [comment]
Fix here: https://github.com/ogri-la/wowman/pull/70

fyi @layday, this also adds the call to `native!` that should get you something nicer on the mac. 

If you guys are keen to see these fixes now and anything else that `0.10.0` brings, then here is an early build: [wowman-0.10.0-unreleased-standalone.jar.zip](https://github.com/ogri-la/wowman/files/3721428/wowman-0.10.0-unreleased-standalone.jar.zip)

(you'll need to remove the `.zip` suffix, github doesn't let you upload `.jar` files)

**Comment by torkus** [comment]
Please re-open ticket if the fix doesn't work for you

**Comment by layday** [comment]
I had to move the jar inside the repo folder before I was able to run it:

```
[..]
Caused by: java.io.FileNotFoundException: resources/query--all-catalog.sql (No such file or directory)
```

Looks much better on mac though ;)

**Comment by torkus** [comment]
> I had to move the jar inside the repo folder before I was able to run it

That's important to know, thank you.

**Comment by torkus** [comment]
> I had to move the jar inside the repo folder before I was able to run it

fixed: https://github.com/ogri-la/wowman/pull/71

fixed `.jar`: [wowman-0.10.0-unreleased-standalone.jar.zip](https://github.com/ogri-la/wowman/files/3721669/wowman-0.10.0-unreleased-standalone.jar.zip)
