### ISSUE TITLE
weirdness with: AGT - Automatic Goblin Therapist

### ISSUE THREAD

**Issue by torkus** [ogri-la/wowman#77]
Two distinct installation directories of AGT exist and it's confounding the update mechanism.

AGT recently refactored the internals of their addon changing the directory name from "AGT" to "AutomaticGoblinTherapist" and changing from version "1_4_5" to "1.05.00".

https://www.curseforge.com/wow/addons/agt-automatic-goblin-therapist/files

The metadata for both is the same, so they're grouped in together in wowman and you only see one that refuses to be updated.

This could be solved by wowman by first uninstalling the old addon and then installing the new one rather than simply overwriting the old one. With the current mechanism it's possible for files to accumulate if introduced in one release then removed in another. It would wipe any state that (shouldn't ever but) may be stored in the addon dir.

Short term fixes for this problem case are deleting and re-installing the addon (*not* just re-installing). Or, deleting the `.wowman.json` files and then choosing the 're-install all' option. The addons that have no match and can't be updated will be revealed and can be managed on case by case basis.

cc @mooreatv

**Comment by torkus** [comment]
oh hey! @mooreatv, you're the same one who opened [this ticket](https://github.com/ogri-la/wowman/issues/29) a while back. Weird coincidence.

**Comment by mooreatv** [comment]
I changed the directory when making the classic version work because I couldn't spot easily AGT in my addons folder (and also I'm used to more descriptive name)

the other reason is it never worked for classic until now so I figured noone had it "installed" for classic and the older directory name wouldn't matter
(it is an issue for bfa but it seems twitch is able to update it fine)

I wouldn't worry _too much_ about one time issue?

**Comment by torkus** [comment]
Hey, thanks for your feedback. It's not a big issue, really, just a problem that may occur with the way wowman installs addons. I think I'm going to change it, but not in the 0.11.0 release.

> ps: very weird I didn't get a notification or email about the tag above

that is weird, I've noticed it a few times myself. Maybe github are dropping the ball somewhere.

I'm not sure if you're interested or not, but I'm adding support for [installing addons from github](https://github.com/ogri-la/wowman/issues/68). It requires a very specific set of requirements but it looks like AGT meets them. Is the process you follow to create a 'compiled' release a standard amongst addon devs or did you copy somebody else? For example, the `pkgmeta` file with instructions on processing the addon and then the github workflows files. It would help if I'm supporting/relying on some existing community norm. Cheers

**Comment by mooreatv** [comment]
I think if you want adoption it'd help to piggyback on the community packager pkgmeta and how it auto puts zip into github releases

I have converted most of my addons for curse to community builds, so they have zip mades for each tag, feel free to check
https://github.com/mooreatv/AuctionDB/releases
https://github.com/mooreatv/NeatMinimap/releases
etc...

Or do you mean you want to package it yourself from git source, in which case you need to grok the pkgmeta (and the variable substitutions)

We should ideally put this in a library so all the various managers can share the same code

**Comment by torkus** [comment]
no, I think I've mis-spoken. 

I was curious to know what process addon developers were following to get a consistent release happening. I figured there must be some community guide out there, or some tool that was using the pkgmeta file. 

I could potentially use that knowledge to improve the github support in wowman.

That's all. I don't want to re-package an addon that doesn't already have a packaged release available, too much of a rabbit hole to go down.

**Comment by layday** [comment]
`pkgmeta` is a build system (which I believe was) created by Curse and `packager` is the community implementation,  which a lot of people use in lieu of Curse's to package and upload their add-ons Curse and WoWI.  The GitHub workflow is modelled on WeakAuras'.

**Comment by mooreatv** [comment]
The bigwigs packager is indeed based on curse's with some additional features and a few diverging things too, the doc is :
https://github.com/BigWigsMods/packager/wiki/Preparing-the-PackageMeta-File

**Comment by torkus** [comment]
Cheers, guys - this is helpful
