### ISSUE TITLE
rename "wowman"

### ISSUE THREAD

**Issue by torkus** [ogri-la/wowman#79]
I'm not sure if I'm soliciting community feedback or not here, but I've never been entirely happy with "wowman", short for "WoW Manager" and I'm thinking of changing it. 

I'm still quite envious of AcidWeb's ["Cursebreaker"](https://github.com/AcidWeb/CurseBreaker) which can't be beaten but perhaps I can avoid losing to it so much.

I'm thinking "strongbox". Not particularly ogri-la themed, but definitely an improvement.

It's different from almost [all of the others](https://github.com/ogri-la/wowman/blob/develop/comrades.csv) out there and doesn't limp off the tongue like "wowman" does.

I'll leave the ticket open for a while, there is no urgency. It will happen prior to the fabled `1.0.0` release. All suggestions welcome.

**Comment by Webxorcist** [comment]
GAS -  Gnome Addon Squad
Cursedeprecator
Cursekiller
BTC - Better than Curse
wowaddonloader
viwp - Very Important WoW Project

I could go on, but it won't get better I'm afraid.

**Comment by torkus** [comment]
> viwp - Very Important WoW Project

this made me laugh ;)

> GAS - Gnome Addon Squad

Some people really get into the Gnome/Goblin thing! When I was trying to come up with a name for this account+profile I wondered what would really get me back into the WoW, like, as enthusiastically as I was about a decade ago? Ogres. Ogre Mages. Smart Ogres, dumb ones, big ones, squidgy ones. I would totally switch to Horde and go full Ogre, fuck yeah. WoW needs more Ogres.

* bonebox
* meatbox
* [meatbag](https://fallout.fandom.com/wiki/Meat_bag) (I kind of like this one)
* ...?

**Comment by mooreatv** [comment]
I'd avoid using "curse" in the name

AGU Automatic Gnomish/Gobling Updater

**Comment by torkus** [comment]
> I'd avoid using "curse" in the name

good thinking

**Comment by torkus** [comment]
went with strongbox 

working happening here: https://github.com/ogri-la/wowman/pull/120
