### ISSUE TITLE
Lots of download failed HTTP 500/502/504 errors

### ISSUE THREAD

**Issue by idddq** [ogri-la/wowman#91]
Here is a picture of it. Latest version is used. 

![Screenshot from 2019-11-25 12-38-11](https://user-images.githubusercontent.com/55606281/69537825-d313be00-0f78-11ea-8b3c-aeae76fa5b75.png)

**Comment by torkus** [comment]
thanks @idddq for using `wowman` and opening a ticket

are you still experiencing this? It *looks* like Curseforge was experiencing a temporary outage to me.

that said, a wall of red text with a technical error message is not very friendly. I'll look into improving that so the cause is clearer.

**Comment by torkus** [comment]
I've created a TODO item for improving the error message. 

Please re-open the ticket if you're still getting error messages
