### ISSUE TITLE
wowman confused by presence of XDG env vars

### ISSUE THREAD

**Issue by layday** [ogri-la/wowman#92]
```
$ echo $XDG_CONFIG_HOME
/Users/layday/.config

$ # Respects $XDG_CONFIG_HOME but does not place config in subdir
$ java -jar wowman-0.10.1-standalone.jar
2019-11-28 12:37:19.017 laydays-mbp INFO [wowman.core:1061] - starting app
2019-11-28 12:37:19.065 laydays-mbp WARN [wowman.core:373] - configuration file not found:  /Users/layday/.config/config.json

$ # Attempts to place config in $PWD with an empty env var - this is contrary to the spec
$ env XDG_CONFIG_HOME= java -jar wowman-0.10.1-standalone.jar
2019-11-28 12:37:37.525 laydays-mbp INFO [wowman.core:1061] - starting app
2019-11-28 12:37:37.573 laydays-mbp WARN [wowman.core:373] - configuration file not found:  /Users/layday/Desktop/config.json

$ # With $XDG_CONFIG_HOME gone
$ env -u XDG_CONFIG_HOME java -jar wowman-0.10.1-standalone.jar
2019-11-28 12:40:13.018 laydays-mbp INFO [wowman.core:1061] - starting app
2019-11-28 12:40:13.082 laydays-mbp WARN [wowman.core:373] - configuration file not found:  /Users/layday/.config/wowman/config.json
```

**Comment by layday** [comment]
ogri-la/wowman@b2ab7af looks like a regression.

**Comment by torkus** [comment]
thanks for the headsup. mac?

**Comment by torkus** [comment]
I suspect this might work:
```clojure
(or (wowman.utils/nilable (System/getenv "XDG_DATA_HOME")) "~/.local/share/wowman")
```

('nilable' is a terrible name, but it basically coerces empty things to nil, like empty strings)

**Comment by torkus** [comment]
> Respects $XDG_CONFIG_HOME but does not place config in subdir

This was deliberate but possibly mistaken. I'll go back and re-read the spec. Probably Sunday

**Comment by layday** [comment]
> mac?

Yeah, but that shouldn't make a difference.

**Comment by torkus** [comment]
> Yeah, but that shouldn't make a difference.

it totally shouldn't, you're right, but I've found the main reason wowman is broken on mac and windows is the path handling - and it's not forwards vs backwards slashes.

**Comment by layday** [comment]
Well now I'm curious, what was it?

**Comment by torkus** [comment]
not sure, I haven't properly investigated yet, but the problems from mac and windows after running the tests seem to stem from paths. looking forward to being less busy in December

**Comment by torkus** [comment]
fixed here: https://github.com/ogri-la/wowman/pull/93

it will be available in the next release, sometime this month hopefully. Let me know if you want a pre-release build.
